# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1go49_FZtS7ITXgwen3kyPuJ8F-BGv2Q6
"""

# Importar las librerias necesarias
!pip install streamlit
import streamlit as st
from PIL import Image
import tensorflow as tf
import numpy as np

model = tf.keras.models.load_model('/content/drive/MyDrive/Python/modeloFashion.keras')
class_labels = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
                'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
st.title('Fashion MNIST Image Classification')

# Subir la imagen
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')
    st.image(image, caption='Uploaded Image.', use_column_width=True)
    st.write("")
    st.write("Classifying...")

    # Preprocesar la imagen para que sea compatible con el modelo
    img = image.resize((28, 28))
    img_array = np.array(img) / 255.0
    img_array = img_array.reshape(1, 28, 28, 1)

    # Realizar predicciones
    prediction = model.predict(img_array)
    predicted_class_index = np.argmax(prediction)

    # Mostrar el resultado
    predicted_class = class_labels[predicted_class_index]
    st.write(f"Prediction: {predicted_class}")